version: '3.8'

services:
  mariadapenha:
    build: .
    container_name: mariadapenha_app
    ports:
      - "8002:8002"
    environment:
      - DJANGO_DEBUG=False
      - DJANGO_SECURE_SSL_REDIRECT=False
      - DJANGO_SESSION_COOKIE_SECURE=False
      - DJANGO_CSRF_COOKIE_SECURE=False
    volumes:
      - "/mariadapenha/mariadapenha/data:/app/data"
      - "/mariadapenha/mariadapenha/staticfiles:/app/staticfiles"
      - "/mariadapenha/mariadapenha/logs:/app/logs"
    restart: unless-stopped
    networks:
      - mariadapenha_network

networks:
  mariadapenha_network:
    driver: bridge