version: '3.8'

services:
  mariadapenha:
    build: .
    container_name: mariadapenha_app
    ports:
      - "8023:8023"                
    environment:
      - DJANGO_DEBUG=False
      - DJANGO_SECURE_SSL_REDIRECT=False
      - DJANGO_SESSION_COOKIE_SECURE=False
      - DJANGO_CSRF_COOKIE_SECURE=False
    restart: unless-stopped
    networks:
      - mariadapenha_network
    volumes:
      - ./data:/app/data


networks:
  mariadapenha_network:
    driver: bridge
